# Site settings

company_name: Big Data AB
address_1: Sveavägen 9, 17th Floor
address_2: 111 57 Stockholm
contact_phone: 08-400 250 20
contact_email: contact@bigdata.se


baseurl: "/resume_test/" # the subpath of your site, e.g. /blog/

url: "http://jtsoi.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude:
  - Makefile
  - readme.md
  - .gitignore
